### ISSUE TITLE
Cordova plugin doesnt finish install

### ISSUE THREAD

**Issue by northkode** [Microsoft/appcenter-sdk-cordova#49] opened 2018-08-08 19:32 UTC
### **Description**

the plugin dies on install 

Please list the steps used to reproduce your issue.

1. install shared plugin via cordova plugin add
2. plugin install dies 

```
Failed to install 'cordova-plugin-appcenter-shared': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone
```

### **Details**

1. Which SDK version are you using?
   latest
2. Which OS version did you experience the issue on?
    -iOS 11
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
   Cordova 7.1

**Comment by jwallra** [comment] 2018-08-09 23:20
Could you provide the full error message you get when you add the plugin?  On your system, can you reproduce the issue on the demoapp included in this repo?

**Comment by bmourat** [comment] 2018-08-10 05:42
@northkode what about versions of other components? I'm interested in Cocoapods and ios-platform
versions

**Comment by northkode** [comment] 2018-08-13 14:48
code-push 2.0.5 "CodePushAcquisition"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-battery-status 2.0.2 "Battery"
cordova-plugin-code-push 1.11.11 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-password-dialog 1.2.0 "Cordova Password Dialog Plugin"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

To replicate create a brand new cordova 7.1 project and install the cordova plugin for analytics and the shared one and it will break.

**Comment by bmourat** [comment] 2018-08-14 04:42
@northkode I could not reproduce this with a new project. The error you provided points to the problem with cocoapods. That is why I'm asking what version of cocoapods are you using? And could you also provide full output of running command 
`cordova plugin add cordova-plugin-appcenter-analytics`

Thanks!

**Comment by bmourat** [comment] 2018-08-21 07:47
Hey @northkode 
We haven't heard from you in a while, did you resolve your issue?

**Comment by bmourat** [comment] 2018-08-30 05:39
Hi @northkode 

I'm gonna close this issue for now, as it lacks info for investigation, but feel free to reopen it anytime!

Best,
Murat

**Closed by bmourat** 2018-08-30 05:39 UTC
