### ISSUE TITLE
AppCenterShared.h:3:9: fatal error: module 'AppCenter' not found

### ISSUE THREAD

**Issue by ghost** [Microsoft/appcenter-sdk-cordova#15] opened 2017-12-28 23:20 UTC
Hi,

I'm getting below error while using Appcenter analytics, any help is appreciated.

```
2017-12-28T22:44:26.1149960Z CompileC /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterShared.o Pricing/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
2017-12-28T22:44:26.1182350Z     cd /Users/vso113500/vsts-agent/_work/4/s/platforms/ios
2017-12-28T22:44:26.1213280Z     export LANG=en_US.US-ASCII
2017-12-28T22:44:26.1246550Z     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/vso113500/vsts-agent/_work/4/s/node_modules/.bin:/Users/vso113500/.taco_home/node_modules/cordova/8.0.0/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/munki"
2017-12-28T22:44:26.1338090Z     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/vso113500/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vso113500/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Index/DataStore -iquote /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-generated-files.hmap -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-own-target-headers.hmap -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-all-target-headers.hmap -iquote /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-project-headers.hmap -I/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator/include -I/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator/usr/local/lib/include -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/DerivedSources/x86_64 -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/DerivedSources -F/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator -include /Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/sharedpch/Pricing-Prefix-abtksipjaymisgazhuebmntepltg/Pricing-Prefix.pch -MMD -MT dependencies -MF /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterShared.d --serialize-diagnostics /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterShared.dia -c /Users/vso113500/vsts-agent/_work/4/s/platforms/ios/Pricing/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.m -o /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterShared.o
2017-12-28T22:44:26.1389800Z In file included from /Users/vso113500/vsts-agent/_work/4/s/platforms/ios/Pricing/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.m:2:
2017-12-28T22:44:26.1410780Z /Users/vso113500/vsts-agent/_work/4/s/platforms/ios/Pricing/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.h:3:9: fatal error: module 'AppCenter' not found
2017-12-28T22:44:26.1428990Z @import AppCenter;
2017-12-28T22:44:26.1447520Z  ~~~~~~~^~~~~~~~~
2017-12-28T22:44:26.1470810Z 1 error generated.
2017-12-28T22:44:26.1483730Z 
2017-12-28T22:44:26.1516400Z CompileC /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterAnalyticsPlugin.o Pricing/Plugins/cordova-plugin-appcenter-analytics/AppCenterAnalyticsPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
2017-12-28T22:44:26.1569210Z     cd /Users/vso113500/vsts-agent/_work/4/s/platforms/ios
2017-12-28T22:44:26.1599560Z     export LANG=en_US.US-ASCII
2017-12-28T22:44:26.1624220Z     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/vso113500/vsts-agent/_work/4/s/node_modules/.bin:/Users/vso113500/.taco_home/node_modules/cordova/8.0.0/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/munki"
2017-12-28T22:44:26.1681370Z     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/vso113500/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vso113500/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Index/DataStore -iquote /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-generated-files.hmap -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-own-target-headers.hmap -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-all-target-headers.hmap -iquote /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Pricing-project-headers.hmap -I/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator/include -I/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator/usr/local/lib/include -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/DerivedSources/x86_64 -I/Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/DerivedSources -F/Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/emulator -include /Users/vso113500/vsts-agent/_work/4/s/platforms/ios/build/sharedpch/Pricing-Prefix-abtksipjaymisgazhuebmntepltg/Pricing-Prefix.pch -MMD -MT dependencies -MF /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterAnalyticsPlugin.d --serialize-diagnostics /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterAnalyticsPlugin.dia -c /Users/vso113500/vsts-agent/_work/4/s/platforms/ios/Pricing/Plugins/cordova-plugin-appcenter-analytics/AppCenterAnalyticsPlugin.m -o /Users/vso113500/Library/Developer/Xcode/DerivedData/Pricing-fcqalxknpqhxryefmyisgmoyqcrl/Build/Intermediates.noindex/Pricing.build/Debug-iphonesimulator/Pricing.build/Objects-normal/x86_64/AppCenterAnalyticsPlugin.o
2017-12-28T22:44:26.1722000Z 
2017-12-28T22:44:26.1737540Z ** BUILD FAILED **
```

Config.xml, AppCenter plugin lists looks like this:
`    <plugin name="cordova-plugin-appcenter-analytics" spec="^0.1.3" />
    <plugin name="cordova-plugin-appcenter-crashes" spec="^0.1.3" />
    <plugin name="cordova-plugin-appcenter-push" spec="^0.1.3" />
    <plugin name="cordova-plugin-cocoapod-support" spec="1.1.1" />`

**Comment by annakocheshkova** [comment] 2017-12-29 08:47
@gananth75 , could you please specify more detailed information regarding the issue: tell us the cordova version you use, describe the steps you followed. Did your application work before?
I assume that there may have been errors during plugin installation (usually they are displayed as yellow messages on mac). Run `cordova platform remove ios`, remove plugins folder, then run `cordova platform add ios` again and make sure that all the plugins have installed correctly and without warnings. If there are, specify them as well.

**Comment by lucamorelli** [comment] 2018-01-14 20:52
I had the same problem, looks like removing the platform, the plugins directory and readding the platform solved the problem

**Comment by max-mironov** [comment] 2018-01-16 11:24
That sounds great @lucamorelli thanks for updating, I'm going to close the issue as it seems to be resolved. But feel free to reach us if you need any help or have more questions.

**Comment by mariomurrent-softwaresolutions** [comment] 2018-11-10 19:10
@annakocheshkova @lucamorelli Does not work for me. Removing and adding the platform does not work. Any ideas?

**Comment by annakocheshkova** [comment] 2018-11-12 07:34
@mariomurrent-softwaresolutions Hi and sorry for the issues you are having!
Could you please repeat this process and send us the logs from the terminal and output window?
Thanks.

**Comment by mariomurrent-softwaresolutions** [comment] 2018-11-12 07:36
Well I just tried to install appcenter-analytics which works fine. The iOS build also works fine, but when I try to run the iOS project I'm getting the error that AppCenter.sh is not found.
I am using ionic-angular 3.9.2, ionic-core 4.12.0

**Comment by annakocheshkova** [comment] 2018-11-12 07:46
@mariomurrent-softwaresolutions open the app folder -> `platforms` -> `ios`. Is there a `Pods/AppCenter` folder?
Also try running `pod update` from there. Does it go successfully?

**Comment by mariomurrent-softwaresolutions** [comment] 2018-11-12 07:48
There is no such folder, altough I did a pod update ...
But the steps are correct, right: Install appcenter-analytics as cordova and npm module. build ios app with ionic, run app with xcode? Or did I miss something?

**Comment by annakocheshkova** [comment] 2018-11-12 08:04
@mariomurrent-softwaresolutions yes everything is correct. 
Is there a Podfile under `platforms\ios` and does it contain the definition for AppCenter?
And how did `pod install` work: what is in the logs?

**Comment by mariomurrent-softwaresolutions** [comment] 2018-11-12 08:06
I will try this again in the evening and let you know :)

**Comment by annakocheshkova** [comment] 2018-11-19 07:11
@mariomurrent-softwaresolutions just a friendly ping, have you tried following the instructions?
Is everything ok now?

**Comment by mariomurrent-softwaresolutions** [comment] 2018-11-19 07:48
Not yet. Havent had that much time to try it, but i will let you know today

**Comment by mariomurrent-softwaresolutions** [comment] 2018-11-20 17:55
Looks good now :) Thank you for your patience

**Comment by annakocheshkova** [comment] 2018-11-20 19:10
Good I'm glad the issue is resolved.
Closing it now, feel free to reopen if you have any issues.

**Closed by annakocheshkova** 2018-11-20 19:10 UTC
Labels: iOS, waiting-for-clarification

**Comment by parthnayak7448** [comment] 2019-03-06 18:11
Hey @annakocheshkova , 

Solutions commented on Nov 12, 2018 works fine for me. 

Thanks

**Comment by parthnayak7448** [comment] 2019-10-04 13:20
hey @annakocheshkova  I am facing following issue in ios 13 ionic 4 
[AppCenter] WARNING: -[MSAuthTokenContext authTokenHistory]/210 Failed to retrieve history state or none was found.

**Comment by annakocheshkova** [comment] 2019-10-04 13:22
@parthnayak7448 this warning is ok. Is there anything particular that doesn't work?

**Comment by parthnayak7448** [comment] 2019-10-04 13:40
@annakocheshkova it showing white screen ionic 4 ios 13.1.1
