### ISSUE TITLE
Error installing Anaytics/Crashes from cordova-plugin-appcenter-shared

### ISSUE THREAD

**Issue by chazguerrero** [Microsoft/appcenter-sdk-cordova#23] opened 2018-01-23 20:14 UTC
``` bash
:CICD-Poc $ cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.drivetime.poc
	Name: CICD-Poc
iOS project created with cordova-ios@4.5.4
Installing "cordova-plugin-appcenter-analytics" for ios
Installing "cordova-plugin-appcenter-shared" for ios
Failed to install 'cordova-plugin-appcenter-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/CICD-Poc/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:9955) UnhandledPromiseRejectionWarning: Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/CICD-Poc/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:9955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9955) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried removing the ios platform and re adding it but error continues to happen.

**Comment by sergey-akhalkov** [comment] 2018-01-30 10:44
Hi @chazguerrero, thanks for reaching us and sorry for the delayed response.

I have several things that we need to clarify to understand what goes wrong:
1. What version of `cordova` are you using?
2. Could you please share your `config.xml` file contents?
3. Could you please perform `cordova platform add ios` command on our [demoapp](https://github.com/Microsoft/appcenter-sdk-cordova/tree/master/demoapp)
 and let me know if you see any issues?

**Comment by chazguerrero** [comment] 2018-02-04 11:59
Hi @sergey-akhalkov 
 let me know if you need anymore info and thank you for the help!
1. cordova version 8.0.0
2. 
``` xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.drivetime.poc" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>CICD-Poc</name>
    <description>An Ionic Framework application for the Ionic Conference.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-navigation href="http://*/*" />
    <allow-navigation href="tel:*" />
    <allow-navigation href="mailto:*" />
    <platform name="android">
        <preference name="APP_SECRET" value="747ec0f1-09c4-4272-834e-9a1a7505755c" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <icon src="resources/android/icon/drawable-xhdpi-icon.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <preference name="APP_SECRET" value="829e4628-290f-4512-904e-f7e3070d1750" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
    </platform>
    <preference name="orientation" value="default" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="StatusBarStyle" value="default" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="^2.3.0">
        <variable name="XWALK_VERSION" value="22+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="true" />
    </plugin>
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.2" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.1.0" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-cocoapod-support" spec="^1.3.0" />
    <plugin name="cordova-plugin-appcenter-crashes" spec="^0.1.3" />
    <plugin name="cordova-plugin-appcenter-analytics" spec="^0.1.3" />
</widget>
```
3. I tried running this on the demoapp and it failed
``` bash
iscovered plugin "cordova-plugin-appcenter-push" in config.xml. Adding it to the project
Installing "cordova-plugin-appcenter-push" for ios
Installing "cordova-plugin-appcenter-shared" for ios
Failed to install 'cordova-plugin-appcenter-push': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/chazguerrero/Documents/GitHub/ThinkLab/appcenter-sdk-cordova/demoapp/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
Failed to restore plugin "cordova-plugin-appcenter-push" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 1

```

**Comment by vilhelmjosander** [comment] 2018-02-05 12:11
I am experiencing a similar issue, though for the "cordova-plugin-appcenter-crashes".

```javascript

Installing "cordova-plugin-appcenter-shared" for ios
Failed to install 'cordova-plugin-appcenter-crashes': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/vilhelmjosander/Development/myproject/app/cordova/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
Failed to restore plugin "cordova-plugin-appcenter-crashes" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 1

```

When trying to build the app with XCode I get the following error:

```
Module 'AppCenter' not found
```

**Cordova version**: 8.0.0

**config.xml**
```
<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="3050201" id="com.myproject.app" ios-CFBundleVersion="1" version="3.5.2" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyProject</name>
    <access origin="*" />
    <access origin="cdvfile://*" />
    <access origin="file://*" />
    <allow-intent href="*" />
    <allow-navigation href="*" />
    <description>
        MyProject app
    </description>
    <author email="vilhelm@myproject.se" href="http://myproject.se">
        MyCompany
    </author>
    <content src="index.html" />
    <feature name="Device">
        <param name="ios-package" value="CDVDevice" />
    </feature>
    <feature name="Notification">
        <param name="ios-package" value="CDVNotification" />
    </feature>
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="Orientation" value="portrait" />
    <preference name="webviewbounce" value="true" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="KeyboardDisplayRequiresUserAction" value="false" />
    <preference name="iosPersistentFileLocation" value="Library" />
    <preference name="AndroidPersistentFileLocation" value="Internal" />
    <preference name="AutoHideSplashScreen" value="true" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="2000" />
    <preference name="FadeSplashScreenDuration" value="1000" />
    <preference name="deployment-target" value="9.0" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="android-compileSdkVersion" value="26" />
    <preference name="BackupWebStorage" value="none" />
    <platform name="ios">
        <config-file parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
            <string>myproject requires permission to access your photo library.</string>
        </config-file>
    </platform>
    <platform name="ios">
        <config-file parent="NSCameraUsageDescription" platform="ios" target="*-Info.plist">
            <string>myproject requires permission to access your photo library and/or cameras.</string>
        </config-file>
    </platform>
    <platform name="ios">
        <config-file parent="NSLocationWhenInUseUsageDescription" platform="ios" target="*-Info.plist">
            <string>myproject needs permission to use your location to store geodata.</string>
        </config-file>
    </platform>
    <platform name="ios">
        <config-file mode="add" parent="ITSAppUsesNonExemptEncryption" target="*-Info.plist">
            <false />
        </config-file>
    </platform>
    <platform name="android">
        <resource-file src="google-services.json" target="app/google-services.json" />
    </platform>
    <platform name="ios">
        <resource-file src="GoogleService-Info.plist" />
    </platform>
    <platform name="ios">
        <preference name="APP_SECRET" value="XXXXXXXX" />
    </platform>
    <platform name="android">
        <preference name="APP_SECRET" value="XXXXXXX" />
    </platform>
    <platform name="android">
        <preference name="CodePushDeploymentKey" value="XXXXXX" />
    </platform>
    <platform name="ios">
        <preference name="CodePushDeploymentKey" value="XXXXXXX" />
    </platform>
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.0" />
    <plugin name="cordova-plugin-sketch" spec="git+https://github.com/MatthewKapteyn/cordova-plugin-sketch.git" />
    <plugin name="cordova-plugin-camera" spec="^4.0.1" />
    <plugin name="cordova-plugin-app-version" spec="^0.1.9" />
    <plugin name="cordova-plugin-device" spec="^2.0.1" />
    <plugin name="cordova-plugin-dialogs" spec="^2.0.1" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="^2.0.1" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-settings-hook" spec="^0.2.7" />
    <plugin name="phonegap-plugin-push" spec="^2.1.2">
        <variable name="FCM_VERSION" value="11.0.1" />
    </plugin>
    <plugin name="cordova-plugin-appcenter-crashes" spec="^0.1.3" />
    <plugin name="cordova-plugin-zip" spec="^3.1.0" />
    <plugin name="cordova-plugin-code-push" spec="^1.11.3" />
    <engine name="android" spec="latest" />
    <engine name="ios" spec="latest" />
</widget>
```

**Comment by vilhelmjosander** [comment] 2018-02-05 12:15
@chazguerrero You would probably want to obfuscate your APP_SECRETs in your example config.xml or change them.

**Comment by vilhelmjosander** [comment] 2018-02-05 16:29
Ok, it was as easy as running `pod repo update` to resolve this for me. I guess I hadn't done that in a while...

**Comment by elamalani** [comment] 2018-02-06 18:43
@chazguerrero Did you happen to fix your issue? Please let us know.

**Comment by chazguerrero** [comment] 2018-02-07 20:26
@vilhelmjosander Thank you for the check, I obfuscated the secrets and changed them. @elamalani I am still having issues the issue now is 

``` bash
/Users/chazguerrero/Documents/GitHub/ThinkLab/CICD-Poc/platforms/ios/CICD-Poc/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.h:3:9: fatal error: 
      module 'AppCenter' not found
@import AppCenter;
 ~~~~~~~^~~~~~~~~
1 error generated.
```

the platform add now works without an error, but the demo app now compiles and runs fine.

Any suggestions on how I can proceed on troubleshooting this issue?

**Comment by sergey-akhalkov** [comment] 2018-02-09 13:02
Hey guys, I've tried to reproduce the issue but with no luck using the sample app in this repo:
```bash
sergeys-mbp:sample sergeyakhalkov$ cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.1
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: com.test.cordovaapp
        Name: App Center Demo
iOS project created with cordova-ios@4.5.4
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-appcenter-analytics" in config.xml. Adding it to the project
Installing "cordova-plugin-appcenter-analytics" for ios
Installing "cordova-plugin-appcenter-shared" for ios
Adding cordova-plugin-appcenter-analytics to package.json
Saved plugin info for "cordova-plugin-appcenter-analytics" to config.xml
Discovered plugin "cordova-plugin-appcenter-analytics-tests" in config.xml. Adding it to the project
Installing "cordova-plugin-appcenter-analytics-tests" for ios
Installing "cordova-plugin-test-framework" for ios
Adding cordova-plugin-appcenter-analytics-tests to package.json
Saved plugin info for "cordova-plugin-appcenter-analytics-tests" to config.xml
Discovered plugin "cordova-plugin-appcenter-crashes" in config.xml. Adding it to the project
Installing "cordova-plugin-appcenter-crashes" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-appcenter-shared" already installed on ios.
Adding cordova-plugin-appcenter-crashes to package.json
Saved plugin info for "cordova-plugin-appcenter-crashes" to config.xml
Discovered plugin "cordova-plugin-appcenter-crashes-tests" in config.xml. Adding it to the project
Installing "cordova-plugin-appcenter-crashes-tests" for ios
Plugin dependency "cordova-plugin-test-framework@1.1.6" already fetched, using that version.
Dependent plugin "cordova-plugin-test-framework" already installed on ios.
Adding cordova-plugin-appcenter-crashes-tests to package.json
Saved plugin info for "cordova-plugin-appcenter-crashes-tests" to config.xml
Discovered plugin "cordova-plugin-appcenter-push" in config.xml. Adding it to the project
Installing "cordova-plugin-appcenter-push" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-appcenter-shared" already installed on ios.
Adding cordova-plugin-appcenter-push to package.json
Saved plugin info for "cordova-plugin-appcenter-push" to config.xml
Discovered plugin "cordova-plugin-appcenter-push-tests" in config.xml. Adding it to the project
Installing "cordova-plugin-appcenter-push-tests" for ios
Plugin dependency "cordova-plugin-test-framework@1.1.6" already fetched, using that version.
Dependent plugin "cordova-plugin-test-framework" already installed on ios.
Adding cordova-plugin-appcenter-push-tests to package.json
Saved plugin info for "cordova-plugin-appcenter-push-tests" to config.xml
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
sergeys-mbp:sample sergeyakhalkov$
```
So please make sure you have updated you prod repos like [suggested](https://github.com/Microsoft/appcenter-sdk-cordova/issues/23#issuecomment-363138546) @vilhelmjosander 

Just in case, here is my environment settings:
```bash
sergeys-mbp:sample sergeyakhalkov$ cordova -v
8.0.0
sergeys-mbp:sample sergeyakhalkov$ pod --version
1.3.1
sergeys-mbp:sample sergeyakhalkov$ npm -v
5.6.0
sergeys-mbp:sample sergeyakhalkov$
```

**Comment by sergey-akhalkov** [comment] 2018-02-09 13:08
@ch2laughlin, as for the new issue you have
```
/Users/chazguerrero/Documents/GitHub/ThinkLab/CICD-Poc/platforms/ios/CICD-Poc/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.h:3:9: fatal error: 
      module 'AppCenter' not found
@import AppCenter;
 ~~~~~~~^~~~~~~~~
1 error generated.
```

Could you please create new issue and provide us as more info as possible, if I get it right this issue has been resolved, so I'm closing this.

Please also let me know if you have any questions or see any issues.

**Closed by sergey-akhalkov** 2018-02-09 13:08 UTC
Labels: analytics, crashes, iOS

**Comment by tiptronic** [comment] 2018-06-22 15:14
I have the exact same problem as @chazguerrero 
```
module 'AppCenter' not found
@import AppCenter;
 ~~~~~~~^~~~~~~~~
1 error generated.
```
both, when creating a fresh project like shown in the appcenter.ms docs, and when following your steps in the demoapp

Is there a new issue already?

**Comment by tiptronic** [comment] 2018-06-22 16:10
@chazguerrero thx for the hint.. where did you put these lines exactly?
(I just created a Podfile manually - like in the swift app - because I ran out of ideas)

**Comment by hchoriq** [comment] 2018-09-13 20:07
If it helps, in our package.json we added hooks that did the pod init and update:

    <platform name="ios">
        <hook src="update_pods.sh" type="before_platform_add" />
        <hook src="install_pods.sh" type="after_platform_add" />

**Comment by studentIvan** [comment] 2019-01-30 12:02
Getting same bug when trying to install cordova-plugin-appcenter-shared 0.3.0

![image](https://user-images.githubusercontent.com/1205208/51979365-080ccc80-249e-11e9-9548-79c288f7afe3.png)

Solved the issue using this:
`cordova plugin add cordova-plugin-cocoapod-support --save`
`cordova platform add ios@https://github.com/apache/cordova-io` (version from master)

and cfg:
```
<platform name="ios">
        <preference name="pods_ios_min_version" value="10.0" />
        <preference name="pods_use_frameworks" value="true" />
        <preference name="deployment-target" value="10.0" />
```

**Comment by annakocheshkova** [comment] 2019-02-04 07:53
@studentIvan this is [this issue](https://github.com/Microsoft/appcenter-sdk-cordova/issues/73#issuecomment-457157145). One more [possible solution to this](https://github.com/Microsoft/appcenter-sdk-cordova/issues/73#issuecomment-458986428).

**Comment by serkon** [comment] 2019-02-08 06:10
Hi there, i get the same issue when run ´ionic cordova platform add ios --verbose´ by the way i don't get error for android, it made on just ios.

´´´bash
...
...
Running command: pod install --verbose
==== pod install start ====

  Preparing


Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Journey`: (``)

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `AppCenter (~> 1.12.0)` required by `Podfile`

Specs satisfying the `AppCenter (~> 1.12.0)` dependency were found, but they required a higher minimum deployment target.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:723:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:721:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

Command finished with error code 1: pod install,--verbose
Failed to install 'cordova-plugin-appcenter-shared': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Volumes/Depo/Work/logo.com.tr/ng-projects/Journey/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
Failed to install 'cordova-plugin-appcenter-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Volumes/Depo/Work/logo.com.tr/ng-projects/Journey/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
pod: Command failed with exit code 1
Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Volumes/Depo/Work/logo.com.tr/ng-projects/Journey/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios --verbose --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 functions +1ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +17ms
´´´

**Comment by annakocheshkova** [comment] 2019-02-08 07:58
@serkon Hi there, please see [this section of the throubleshhoting page](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/cordova#failed-to-install-plugin---pod-command-failed-with-exit-code-1).
