### ISSUE TITLE
Analytics doesn't show up in the AppCenter on iOS

### ISSUE THREAD

**Issue by dbpprt** [microsoft/appcenter-sdk-cordova#71] opened 2019-01-23 15:38 UTC
### **Description**

I implemented the analytics sdk for my cordova application on iOS and Android. It works fine on Android but on iOS I do not have any metrics being shown in the appcenter analytics pane.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install SDK and set APP_SECRET
2. Run on iOS
3. Test the SDK

window.AppCenter.Analytics.isEnabled(() => showDebugDialog('is enabled'), (err: any) => showDebugDialog('not enabled ' + err));
        window.AppCenter.Analytics.trackEvent('Object opened', null, () => showDebugDialog('success'), (err: any) => showDebugDialog(err));

(both shows success)

4. Go to appcenter diagnostic pane => nothing shows up.

### **Details**

1. Which SDK version are you using?
    - 0.3.0
2. Which OS version did you experience the issue on?
    - iOS 12.1.2
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova 6.5.0
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    - iPhone 6s Plus / iPhone 8 Plus
5. What third party plugins are you using?
  <plugin name="cordova-plugin-cocoapod-support" />
  <plugin name="cordova-plugin-x-socialsharing" spec="5.4.0" />
  <plugin name="cordova-clipboard" spec="^1.2.1" />
  <plugin name="cordova-plugin-x-toast" spec="^2.6.2" />
  <plugin name="cordova-plugin-android-permissions" />
  <plugin name="cordova-ios-plugin-no-export-compliance" spec="0.0.5" />
  <plugin name="tabris-plugin-camera" spec="https://github.com/eclipsesource/tabris-plugin-camera.git" />

**Comment by annakocheshkova** [comment] 2019-01-24 11:52
@dennisbappert thanks for reporting this to us!
However, I can't reproduce your issue and can see "Object clicked" show up in App Center.

First of all, could you please go to `platforms` > `ios` > `HelloCordova` > `Plugins` and check if `cordova-plugin-appcenter-analytics` is there?

I am aware that with `0.3.0` version dropping iOS 8 support, there may be some issues during installation process and that can lead to plugins not installing fully.
I see in another thread that you already managed to resolve it by changing deployment target to 9.0, but if analytics plugin didn't install completely, you can try to do the following:
Delete all App Center plugin folders in
- `platforms > ios > HelloCordova > plugins`
- `platforms > ios > www > plugins`
- `plugins`
Make sure that you *do not* delete the Podfile.
re-run `cordova plugin add appcenter-analytics`

**Comment by dennisbappert** [comment] 2019-01-24 13:06
It is there, as I mentioned:

```
window.AppCenter.Analytics.isEnabled(() => showDebugDialog('is enabled'), (err: any) => showDebugDialog('not enabled ' + err));
window.AppCenter.Analytics.trackEvent('Object opened', null, () => showDebugDialog('success'), (err: any) => showDebugDialog(err));
```

Both methods indicate success which shows that all dependencies are loaded.

**Comment by annakocheshkova** [comment] 2019-01-24 13:31
@dennisbappert Are you using XCode or terminal to run the app?

**Comment by dennisbappert** [comment] 2019-01-24 13:42
Deployed through Testflight on various devices as in my initial description.

**Comment by annakocheshkova** [comment] 2019-01-24 13:57
Sorry, don't see any mentions of Testflight in issue description :) Maybe I missed it.
Anyway, I'm assuming you can debug through XCode, so could you please open `Plugins` > `AppCenterAnalyticsPlugin.m`, put a breakpoint in `trackEvent` method and see if it gets there?

Unfortunately, I am not able to reproduce your issue so it's the only way I can help you.
You could also send me a minimal working version of your applciation so that I can debug it and see what the issue is.

Thanks!

**Comment by dennisbappert** [comment] 2019-01-24 14:51
Unfortunately I'm using only a headless OSX build agent and I'm not able to debug the code. From my technical understanding and from looking into the code in case the methods mentioned above:

window.AppCenter.Analytics.isEnabled
window.AppCenter.Analytics.trackEvent

will only fire the callback if the communication with the plugin was successful.

**Comment by annakocheshkova** [comment] 2019-01-24 16:33
@dennisbappert yes this is correct. 
From what you are describing looks like everything is fine.
Although I should warn you, native ios sdk does not report 401 errors back to cordova, so if you, say, mistype app secret or accidentally put it in the `config.xml` the wrong way, success callback will still fire (just checked it).

If you are not able to debug, do you have access to the application logs then? Or something to trace back the issue?

**Comment by dennisbappert** [comment] 2019-01-24 17:54
I already created a new test application and pasted the new secret, doesn't work. How can I read the logs from an iOS device? Can you check the application logs from appcenter to see if any request are coming in? I can share my client ip address if required.

**Comment by annakocheshkova** [comment] 2019-01-24 18:24
Can you share with me a snippet of how you pasted the secret in config?
If you are using a simulator, you can [see the logs in console](https://wiki.appcelerator.org/display/guides2/Native+iOS+Debugging+and+Testing+Tools#NativeiOSDebuggingandTestingTools-ViewlogoutputinConsole). 
You can see logs from XCode as well but I'm assuming you can't use it.
And finally you can [get the logs this way](https://stackoverflow.com/a/19148654/7453375).

Thanks!

**Comment by dennisbappert** [comment] 2019-01-24 19:09
```
 <platform name="ios">
    <preference name="APP_SECRET" value="xxxxxxxx-401c-43f0-bf77-76be6a54016c" />
     ....
</platform>
``` 
I'm setting up the build on a physical macbook to get the logs with the emulator, will take some time. All builds are running on headless cloud machines.

**Comment by jwallra** [comment] 2019-01-24 19:32
Typically you can capture logs with the "Console" application.  I'm not sure if you are able to run it on your build agent, but if you can set up the build locally you should be able to capture logs and then filter using "AppCenter".  If you message us on the App Center portal using Intercom (the chat bubble in the lower right) we'll be able to see your app secret without posting it here.  Mention my name (Jacob Wallraff) and it should get to me quicker 😄

**Comment by dennisbappert** [comment] 2019-01-24 19:58
> Typically you can capture logs with the "Console" application. I'm not sure if you are able to run it on your build agent, but if you can set up the build locally you should be able to capture logs and then filter using "AppCenter". If you message us on the App Center portal using Intercom (the chat bubble in the lower right) we'll be able to see your app secret without posting it here. Mention my name (Jacob Wallraff) and it should get to me quicker 😄

I started a new conversation (already have a few).

**Comment by dennisbappert** [comment] 2019-01-24 20:11
```
[AppCenter] ERROR: -[MSAppCenter startService:withAppSecret:transmissionTargetToken:andSendLog:fromApplication:]/370 Cannot start service MSCrashes. App Center was started without app secret, but the service requires it.
```

Here you go, but the secret is in the config in the exact same way as for the android platform and android works fine.

**Comment by jwallra** [comment] 2019-01-24 23:38
Hmm, that's weird.  You have 2 separate apps in the portal for iOS and android, correct?  As long as you have your config set up like in the docs (see below) then you should be good:

```<platform name="android">
   <preference name="APP_SECRET" value="{Your Android app secret}" />
</platform>
<platform name="ios">
   <preference name="APP_SECRET" value="{Your iOS app secret}" />
</platform>```

Otherwise, we're starting to look into things on the backend to see if there's a problem.

**Comment by dennisbappert** [comment] 2019-01-25 06:44
Yes I have two AppCenter apps and my configuration looks exactly like this.

I grabbed the logs by using console and emulator. I also checked the build artifacts from my Cordova build and I was able to find the app secret in the temporary target directory. Where is the app secret stored in the final IPA?

**Comment by dennisbappert** [comment] 2019-01-25 09:45
There is a single logline shown:
```
[AppCenter] ERROR: -[MSAppCenter startService:withAppSecret:transmissionTargetToken:andSendLog:fromApplication:]/370 Cannot start service MSCrashes. App Center was started without app secret, but the service requires it.
```

I unpacked the IPA file and looked into the root directory: the config.xml contains the correct app_secret.

**Comment by annakocheshkova** [comment] 2019-01-25 10:21
@dennisbappert did you enable verbose logging? There definitely should be more logs coming from App Center.

**Comment by dennisbappert** [comment] 2019-01-26 14:33
How can I enable verbose logging? There is nothing more in the logs.

**Comment by serkon** [comment] 2019-01-27 16:03
I am getting this errors on terminal while installing cordova appcenter plugin
command:  `cordova plugin add cordova-plugin-appcenter-analytics`

ERRORS:

```bash
$ cordova plugin add cordova-plugin-appcenter-analytics
Installing "cordova-plugin-appcenter-analytics" for android
Installing "cordova-plugin-appcenter-shared" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-appcenter-analytics" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.3.0" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for ios
Failed to install 'cordova-plugin-appcenter-shared': undefined
Failed to install 'cordova-plugin-appcenter-analytics': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by annakocheshkova** [comment] 2019-01-28 10:46
@dennisbappert my bad, this is not implemented for cordova yet.
Please go to `platforms > ios > <AppName> > Plugins > cordova-plugin-appcenter-shared > AppCenterShared.m`, and in `configureWithSettings` method, at the bottom, paste 
`[MSAppCenter setLogLevel:MSLogLevelVerbose];`
The run the app and share the logs with us again.

Thanks!

**Comment by annakocheshkova** [comment] 2019-01-28 10:48
@serkon I don't see how this is related to this issue. 
Could you please make sure that you are not running into [this issue](https://github.com/Microsoft/appcenter-sdk-cordova/issues/73). 
If not, please open a separate issue in our repository.

**Comment by dennisbappert** [comment] 2019-01-28 10:51
You can close the issue, we decided to not go with App Center as most of the functionality seems unreliable.

**Closed as completed** 2019-01-28 16:28 UTC

**Comment by giacomodeglinnocenti** [comment] 2019-08-06 09:28
platforms/ios

` pod repo update`

before any operations.

In case of difficulties to uninstall a previous broken version, follow @annakocheshkova instructions
